name: Deploy Cognite Function
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy:
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test code
        run: echo "AlL tEStS PaSsED"
      - name: Deploy
        uses: andeplane/deploy-function-action@master
        with:
          cdf_project: andershaf
          cdf_base_url: https://api.cognitedata.com
          cdf_credentials: ${{ secrets.COGNITE_API_KEY }}
          handler_path: example/handler.py
      - name: Run integration tests
        run: echo "AlL tEStS PaSsED"
